name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analyzing the code with pylint
      run: |
        CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD -- '*.py')
        if [ -n "$CHANGED_FILES" ]; then
          EXISTING_FILES=$(echo "$CHANGED_FILES" | xargs -I {} bash -c 'if [ -f "{}" ]; then echo "{}"; fi')
          if [ -n "$EXISTING_FILES" ]; then
            echo "Running pylint on changed files:"
            echo "$EXISTING_FILES"
            pylint $EXISTING_FILES
          else
            echo "No existing Python files to lint, skipping pylint."
          fi
        else
          echo "No Python files changed, skipping pylint."
        fi
